#!/bin/bash

setupDummyMonitor(){

    echo $1
    xrandr --setmonitor default 640/254x480/480+0+0 $1
    xrandr --setmonitor test2 640/254x480/480+640+0 none
    xrandr --fb 1024x480
    xrandr
}
D=:7
echo $1
if [ "$1" = "--no-xserver" ];then
	shift
else
    Xvfb -noreset -r +extension RANDR -screen 0 1024x480x24 $D &> /dev/null & pid="$!"

    export DISPLAY=$D
    if [ "$1" = "--fake-monitors" ];then
        shift
        sleep 1s
        setupDummyMonitor $(xrandr |grep " connected" |cut -d" " -f1) &> /dev/null
    fi
fi
DISPLAY=$D $@
exitCode=$?
[ "$pid" ] && kill "$pid" 
exit $exitCode
