/**
 * @file globals.c
 * @copydoc globals.h
 */
#include <X11/extensions/XInput2.h>
#include <xcb/xinput.h>

#include "globals.h"

bool RUN_AS_WM = 1;
bool STEAL_WM_SELECTION = 0;


bool LOAD_SAVED_STATE = 1;

long KILL_TIMEOUT = 100;


int ROOT_EVENT_MASKS = XCB_EVENT_MASK_SUBSTRUCTURE_REDIRECT | XCB_EVENT_MASK_SUBSTRUCTURE_NOTIFY |
                       XCB_EVENT_MASK_STRUCTURE_NOTIFY;

int NON_ROOT_EVENT_MASKS = XCB_EVENT_MASK_PROPERTY_CHANGE | XCB_EVENT_MASK_VISIBILITY_CHANGE;

int KEYBOARD_MASKS = XCB_INPUT_XI_EVENT_MASK_KEY_PRESS | XCB_INPUT_XI_EVENT_MASK_KEY_RELEASE;
int POINTER_MASKS = XCB_INPUT_XI_EVENT_MASK_BUTTON_PRESS | XCB_INPUT_XI_EVENT_MASK_BUTTON_RELEASE |
                    XCB_INPUT_XI_EVENT_MASK_MOTION;

int ROOT_DEVICE_EVENT_MASKS = XCB_INPUT_XI_EVENT_MASK_HIERARCHY | XCB_INPUT_XI_EVENT_MASK_BUTTON_PRESS;
int NON_ROOT_DEVICE_EVENT_MASKS = XCB_INPUT_XI_EVENT_MASK_FOCUS_OUT | XCB_INPUT_XI_EVENT_MASK_FOCUS_IN;

int DEFAULT_NUMBER_OF_WORKSPACES = 10;
int DEFAULT_NUMBER_OF_HIDDEN_WORKSPACES = 1;

int IGNORE_MASK = Mod2Mask;
int DEFAULT_MOD_MASK = Mod4Mask;

int DEFAULT_BORDER_WIDTH = 1;
int DEFAULT_BORDER_COLOR = 0x0;

int DEFAULT_FOCUS_BORDER_COLOR = 0x00FF00;
int DEFAULT_UNFOCUS_BORDER_COLOR = 0xDDDDDD;

bool IGNORE_SEND_EVENT = 0;
bool IGNORE_KEY_REPEAT = 0;

bool SYNC_FOCUS = 1;

char* SHELL = "/bin/sh";

int CLONE_REFRESH_RATE = 15;

int SYNC_WINDOW_MASKS = 0;

int DEFAULT_WINDOW_MASKS = INPUT_MASK;

int DEFAULT_BINDING_MASKS = XCB_INPUT_XI_EVENT_MASK_KEY_PRESS;

int DEFAULT_WORKSPACE_INDEX = 0;


unsigned int CRASH_ON_ERRORS = 0;

int AUTO_FOCUS_NEW_WINDOW_TIMEOUT = 5000;

bool IGNORE_SUBWINDOWS = 1;

int POLL_COUNT = 3;
int POLL_INTERVAL = 10;
int EVENT_PERIOD = 100;

int DEFAULT_MODE = NORMAL_MODE;

char* MASTER_INFO_PATH = "$HOME/.mpxmanager/master-info.txt";
char* CLIENT[] = {"CLIENT_KEYBOARD", "CLIENT_POINTER"};
bool SPAWN_ENV = 1;
bool LD_PRELOAD_INJECTION = 0;
char* LD_PRELOAD_PATH = "/usr/lib/libmpx-patch.so";

int DEFAULT_POINTER = 2;
int DEFAULT_KEYBOARD = 3;

void (*startUpMethod)(void);
void (*postStartUpMethod)(void);
void (*printStatusMethod)(void);
int statusPipeFD[4];

///Last registered event
static void* lastEvent;
void setLastEvent(void* event){
    lastEvent = event;
}
void* getLastEvent(void){
    return lastEvent;
}
